#!/usr/bin/env bash
# Generate the `large` test vault and upload it as a GitHub release asset.
#
# Usage:
#   scripts/upload_test_vault.sh                 # tag: v0.1.0-fixtures
#   scripts/upload_test_vault.sh v0.2.0-fixtures # explicit tag
#
# This script is intentionally separate from the generator so the upload step
# can be run with different credentials (gh auth) than the generator itself.
# Re-running with a tag that already exists is a no-op for the release
# create; pass a new tag to ship a refreshed asset.
#
# Requires: uv, gh (authenticated against the target repo).

set -euo pipefail

TAG="${1:-v0.1.0-fixtures}"
OUT_DIR="${OUT_DIR:-./out/vault-large}"
SEED="${SEED:-42}"

if ! command -v gh >/dev/null; then
  echo "error: gh CLI not found on PATH" >&2
  exit 1
fi
if ! command -v uv >/dev/null; then
  echo "error: uv not found on PATH" >&2
  exit 1
fi

echo ">> Generating ${OUT_DIR} at size=large seed=${SEED} (~1 GB; expect 2–5 min)"
rm -rf "${OUT_DIR}" "${OUT_DIR}.zip"
uv run python scripts/gen_test_vault.py \
  --size large \
  --seed "${SEED}" \
  --output "${OUT_DIR}" \
  --zip

ZIP_PATH="${OUT_DIR}.zip"
if [[ ! -f "${ZIP_PATH}" ]]; then
  echo "error: expected ${ZIP_PATH} to exist after generation" >&2
  exit 1
fi

ZIP_BYTES=$(stat -f%z "${ZIP_PATH}" 2>/dev/null || stat -c%s "${ZIP_PATH}")
echo ">> Zip ready: ${ZIP_PATH} (${ZIP_BYTES} bytes)"

echo ">> Creating GitHub release ${TAG}"
gh release create "${TAG}" \
  "${ZIP_PATH}" \
  --title "${TAG#v} test fixtures" \
  --notes "10k-file / 1 GB Obsidian-style vault for ki functional + perf tests. Generated by \`scripts/gen_test_vault.py --size large --seed ${SEED}\`."

echo ">> Done."
echo "   Asset URL (after release publishes):"
echo "   https://github.com/zach-blumenfeld/knowledge-index/releases/download/${TAG}/$(basename "${ZIP_PATH}")"
